#SPDX-FileCopyrightText: 2023 Martin Helwig
#
#SPDX-License-Identifier: MIT

name: 🐛 Bug Report
description: Create an issue to report a bug
labels: ["bug"]

body:
- type: markdown
  id: greeting
  attributes:
    value: |
      :star: ***Thank you for creating a bug report! Use the sections below to submit a bug report.***

      > [!important]  
      Please do not report security vulnerabilities through public issues, discussions, or pull requests.
      Follow these instruction to report security issues: [Security Policy](../security/policy).

- type: textarea
  id: bug-description
  attributes:
    label: Bug description
    description: Describe the problem as precisely as possible.
    placeholder: Tell us what is the bug.
  validations:
    required: true

- type: textarea
  id: reproduce-steps
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: Do the following to reproduce the behavior.
  validations:
    required: false

- type: textarea
  id: how-to-fix
  attributes:
    label: Possible fixes or solutions
    description: List any possible fixes/suggestions you can think of to solve this problem.
    placeholder: Tell us your ideas to solve the problem.
  validations:
    required: false

- type: dropdown
  id: contribute
  attributes:
    label: Are you interested in contributing a sulution?
    description: Are you interested in implementing a solution to this problem yourself and submitting a pull request?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: false

- type: textarea
  id: additional-information
  attributes:
    label: Additional informations
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

- type: dropdown
  id: terms
  attributes:
    label: By submitting this issue, you agree to follow our Code of Conduct.
    description: I agree to follow this project's [Code of Conduct](../?tab=coc-ov-file#readme).
    options:
      - 'Yes'
  validations:
    required: true
