#SPDX-FileCopyrightText: 2023 Martin Helwig
#
#SPDX-License-Identifier: MIT

blank_issues_enabled: false
contact_links:
  - name: Informations
    url: https://MartinHelwig.github.io/auto-mouse/
    about: Please use this to get more informations.
