#SPDX-FileCopyrightText: 2023 Martin Helwig
#
#SPDX-License-Identifier: MIT

name: â­ Feature Request
description: Create an issue to request a new feature
labels: ["feature"]

body:
- type: markdown
  id: greeting
  attributes:
    value: |
      :star: ***Thank you for creating a feature request! Use the sections below to submit your request.***

      > [!important]  
      Please do not report security vulnerabilities through public issues, discussions, or pull requests.
      Follow these instruction to report security issues: [Security Policy](../security/policy).

- type: textarea
  id: feature-description
  attributes:
    label: Feature description
    description: Describe the feature as precisely as possible.
    placeholder: Tell us what feature you request.
  validations:
    required: true

- type: dropdown
  id: contribute
  attributes:
    label: Are you interested in contributing a sulution?
    description: Are you interested in implementing a solution to this problem yourself and submitting a pull request?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: false

- type: textarea
  id: additional-information
  attributes:
    label: Additional informations
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

- type: dropdown
  id: terms
  attributes:
    label: By submitting this issue, you agree to follow our Code of Conduct.
    description: I agree to follow this project's [Code of Conduct](../?tab=coc-ov-file#readme).
    options:
      - 'Yes'
  validations:
    required: true
