# SPDX-FileCopyrightText: 2023 Martin Helwig
#
# SPDX-License-Identifier: MIT

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    permissions:
      contents: read
      packages: write
      checks: write
      actions: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: "0" # to get the authors summary

      - name: Set Project Name
        run: |
          echo MY_PROJECTNAME=$(pwd | xargs basename) >> $GITHUB_ENV
          echo "# Project $(pwd | xargs basename)" >> $GITHUB_STEP_SUMMARY

      - name: Set up JDK 11
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Prepare Build environment
        run: |
          sudo apt-get install nsis

      - name: Check REUSE compliance
        run: |
          echo "pip install reuse" > install.sh && chmod +x install.sh && ./install.sh && rm install.sh
          echo "## REUSE Compliance" >> $GITHUB_STEP_SUMMARY
          echo "For more information about REUSE see [official page](https://reuse.software/)."
          reuse lint | sed  s'/# /### /g' >> $GITHUB_STEP_SUMMARY
          
      - name: Build With Maven
        run: xvfb-run mvn -B package -Dmaven.test.skip=false -Djavadoc.skip=false -Dource.skip=false -Ddependency-check.skip=false -Dnsis.skip=false

      - name: Add Headline Job Summary
        run: echo "## JUnit " >> $GITHUB_STEP_SUMMARY
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@75b84e78b3f0aaea7ed7cf8d1d100d7f97f963ec # v4.0.0
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: target/surefire-reports/TEST-*.xml
          detailed_summary: true
          include_passed: true
          fail_on_failure: true
          require_tests: true

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@b08db7d89b6bf9e3ea3c2bba7735e2e7faf02282 # v4.9
        with:
          coverage_results_path: target/reports/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: ${{ env.MY_PROJECTNAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false
        
      - name: Add Coverage Job Summary
        run: echo "## Code Coverage ${{ env.coveragePercentageString }}" >> $GITHUB_STEP_SUMMARY

      - name: Add Authors Summary
        run: |
          echo "## Authors Summary" >> $GITHUB_STEP_SUMMARY
          git shortlog -sce --all >> $GITHUB_STEP_SUMMARY
        
      - name: Upload Package
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: auto-mouse_package
          path: target/*.tar.gz
          if-no-files-found: error

      - name: Upload Installer
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: auto-mouse_installer
          path: target/*.exe
          if-no-files-found: error

      - name: Publish to GitHub Packages Apache Maven
        run: xvfb-run mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
