# SPDX-FileCopyrightText: 2023 Martin Helwig
#
# SPDX-License-Identifier: MIT

# This workflow will execute a dependency-check

name: Dependency Check

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * SUN

# Declare default permissions as read only.
permissions: read-all

jobs:
  dependency:
    name: Dependency Check
    permissions:
      contents: write # required by: maven-dependency-submission-action
      packages: none
      checks: none
      actions: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      
    - name: Set up JDK 11
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Dependency Check
      run: xvfb-run mvn -B dependency-check:check -Ddependency-check.skip=false --no-transfer-progress

    - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3 # v3.0.2
