# SPDX-FileCopyrightText: 2023 Martin Helwig
#
# SPDX-License-Identifier: MIT

# This workflow will execute a dependency-check

name: Dependency Check

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * SUN

jobs:
  Dependency-Check:
    permissions:
      contents: write
      packages: write
      checks: write
      actions: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set project name
      run: echo MY_PROJECTNAME=$(pwd | xargs basename) >> $GITHUB_ENV
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Prepare Build environment
      run: ant -noinput -buildfile build.xml prepare-environment

    - name: Dependency Check with Ant
      run: xvfb-run ant -noinput -lib build-environment/ant-libraries -buildfile build.xml dependency-check

    - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
            
