# SPDX-FileCopyrightText: 2023 Martin Helwig
#
# SPDX-License-Identifier: MIT

name: GraalVM Native Image builds

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Native Image on Windows
    permissions:
      contents: read
      packages: none
      checks: none
      actions: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        
      - name: Set up JDK 11
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Prepare environment
        run: ant -noinput -buildfile build.xml prepare-environment
        
      - name: Build with Ant
        run: ant -noinput -lib build-environment/ant-junitlauncher-1.10.13.jar -buildfile build.xml
      
      - uses: graalvm/setup-graalvm@5393c3d80982e8a7fa61005137824ef53731ff9a # v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build windows executable
        run: |
          #native-image -H:Path=build/native -cp 'target/distribution/auto-mouse-1.0.0.jar;target/lib/*' -H:ConfigurationFileDirectories=src/main/config -jar target/distribution/auto-mouse-1.0.0.jar -H:+ReportExceptionStackTraces
          native-image -H:Path=build/native -cp 'target/distribution/auto-mouse-1.0.0.jar;target/lib/commons-logging.jar' -H:ConfigurationFileDirectories=src/main/config -jar target/distribution/auto-mouse-1.0.0.jar -H:+ReportExceptionStackTraces
      
      - name: Upload package
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: auto-mouse
          path: |
            build/native/**
          if-no-files-found: error
