# SPDX-FileCopyrightText: 2023 Martin Helwig
#
# SPDX-License-Identifier: MIT

# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
  
    - name: Publish GitHub Page
      run: xvfb-run mvn clean site site:stage scm-publish:publish-scm --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Publish To GitHub Packages Apache Maven
      run: xvfb-run mvn deploy --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ github.token }}
