# SPDX-FileCopyrightText: 2024 Martin Helwig
#
# SPDX-License-Identifier: MIT

name: Recreate Cache

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Recreate Cache
    permissions:
      contents: write
      packages: none
      checks: none
      actions: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Generate New Uuid
        run: |
          sed -i -E 's/[a-fA-F0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}//' src/cache/cache.info
          sed -i '/^$/d' src/cache/cache.info
          uuidgen >> src/cache/cache.info
          
      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true
          cache-dependency-path: src/cache/cache.info

      - name: Resolve Dependenies & Update Database
        run: xvfb-run mvn -B dependency:resolve dependency:resolve-plugins dependency-check:update-only -Ddependency-check.skip=false --no-transfer-progress

      - name: Prepare Build Environment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push New Uuid
        run: |
          git add src/cache/cache.info
          git commit -m "add new uuid to recreate cache"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
